server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:54321/files
    username: postgres
    password: postgres
    driven-class_name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
    client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/
        registerWithEureka: true
        fetchRegistry: true