spring:
  datasource:
    url: jdbc:postgresql://localhost:54322/users
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
            show-sql: true
            properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect