spring:
  datasource:
    url: jdbc:postgresql://localhost:54322/files
    username: postgres
    password: Postgres2023?
    driven-class_name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect