 #MongoDB
 server:
   port: 8086
spring:
  data:
    mongodb:
      uri: mongodb+srv://lexus:01234@cluster0.95poztr.mongodb.net/?retryWrites=true&w=majority
      database: service-posts

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true