spring:
  datasource:
    url: jdbc:postgresql://localhost:54322/favorites
    username: postgres
    password: Postgres2023?
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
