 #MongoDB
 server:
   port: 8082
spring:
  data:
    mongodb:
      uri: mongodb+srv://lexus:12345@cluster0.5zyasju.mongodb.net/?retryWrites=true&w=majority
      database: service-posts
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
